const BACKEND_API_URL = process.env.REACT_APP_BACKEND_API_URL
const SITE_KEY_RECAPTCHA = process.env.REACT_APP_SITE_KEY_RECAPTCHA
const SOCKET_SERVER = process.env.REACT_APP_SOCKET_SERVER

export { BACKEND_API_URL, SITE_KEY_RECAPTCHA, SOCKET_SERVER }
